name: Feature request
description: Предложить улучшение
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Задача
      description: Какую проблему решает предложение?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы
      description: Рассматривали ли другие варианты?
